version: '2.4'

volumes:
  static_volume:

services:

  nginx:
    image: portfolio/nginx_prod
    build: ../webhost/nginx
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

  web:
    restart: always
    image: portfolio/web_prod
    build:
      context: ../webhost
      dockerfile: ./Docker/Dockerfile.prod
    volumes:
      - static_volume:/code/staticfiles
    expose:
      - 8000
    env_file:
      - ../webhost/.env.prod

